// Generated by GenSettings; DO NOT EDIT
package protocolgen;
public class TsSrcEnums {
	static {
		new TsEnumRef("AssertionType", "ui/popup/displayTestAdditionModal.ts", new String[] {"Exact Match", "Set Comparison", "Smoke Test"});
		new TsEnumRef("AstListDirection", "ui/popup/displayAstModal.ts", new String[] {"downwards", "upwards"});
		new TsEnumRef("ChangeType", "model/test/TestManager.ts", new String[] {"added-test", "updated-test", "removed-test", "test-status-update"});
		new TsEnumRef("ColorType", "ui/getThemedColor.ts", new String[] {"window-border", "probe-result-area", "syntax-type", "syntax-attr", "syntax-modifier", "syntax-variable", "separator", "ast-node-bg", "ast-node-bg-hover"});
		new TsEnumRef("HelpType", null, new String[] {"general", "recovery-strategy", "probe-window", "magic-stdout-messages", "ast-cache-strategy", "syntax-highlighting", "main-args-override", "customize-file-suffix", "property-list-usage", "show-all-properties", "group-properties-by-aspect", "duplicate-probe-on-attr", "capture-stdout", "capture-traces", "location-style", "ast", "test-code-vs-codeprober-code"});
		new TsEnumRef("SyntaxHighlightingLanguageId", null, new String[] {"plaintext", "abap", "apex", "azcli", "bat", "bicep", "cameligo", "clojure", "coffeescript", "c", "cpp", "csharp", "csp", "css", "dart", "dockerfile", "ecl", "elixir", "flow9", "fsharp", "go", "graphql", "handlebars", "hcl", "html", "ini", "java", "javascript", "julia", "kotlin", "less", "lexon", "lua", "liquid", "m3", "markdown", "mips", "msdax", "mysql", "objective-c", "pascal", "pascaligo", "perl", "pgsql", "php", "postiats", "powerquery", "powershell", "proto", "pug", "python", "qsharp", "r", "razor", "redis", "redshift", "restructuredtext", "ruby", "rust", "sb", "scala", "scheme", "scss", "shell", "sol", "aes", "sparql", "sql", "st", "swift", "systemverilog", "verilog", "tcl", "twig", "teal", "typescript", "vb", "xml", "yaml", "json"});
		new TsEnumRef("TabType", "ui/popup/displayTestDiffModal.ts", new String[] {"output", "node", "source", "settings"});
		new TsEnumRef("TextSpanStyle", "ui/create/createTextSpanIndicator.ts", new String[] {"full", "full-compact", "lines", "lines-compact", "start", "start-line"});
	}
}
