#!/bin/sh
set -e

rm -rf build_tmp/
mkdir build_tmp

echo "Gathering sources.."
find src -name "*.java" > sources.txt

echo "Building.."
# "Our own" class files
javac @sources.txt -cp libs/json.jar -d build_tmp -source 8 -target 8
# Third party class files
unzip libs/json.jar '*.class' -x */* -d build_tmp
# Resources
cp -r src/codeprober/resources build_tmp/codeprober/

cd build_tmp

echo "Generating jar.."
echo "Main-Class: codeprober.CodeProber" >> Manifest.txt

VERSION=$(git rev-parse --short HEAD)
echo "Git-Version: $VERSION" >> cpr.properties
if output=$(git status --porcelain) && [ -z "$output" ]; then
  echo "Git status is clean, this build can be released"
  echo "Git-Status: CLEAN" >> cpr.properties
  DST=../../code-prober.jar
  # VERSION is used to check when new versions are available
  # Only set it for release builds
  echo "## Automatically generated by server/build.sh. DO NOT MOIDFIFY\n$VERSION" > ../../VERSION
else
  echo "Git status is non-clean, this is a development build"
  echo "Git-Status: DIRTY" >> cpr.properties
  DST=../../code-prober-dev.jar
fi

if hash date 2>/dev/null; then
  echo "Build-Time: $(date -u +%s)" >> cpr.properties
fi

jar cfm $DST Manifest.txt cpr.properties **/*

cd ..

echo "Cleaning up.."
rm sources.txt
rm -rf build_tmp

echo "Done! Built '$DST'"

if [ x$TEST_SERVER != x ]; then
    echo "Testing..."
    TESTLIBS=src-test/:/usr/share/java/junit4.jar:src/${DST}:libs/json.jar
    echo javac -cp ${TESTLIBS} `find src-test -name "*.java"` || exit 1
    javac -cp ${TESTLIBS} `find src-test -name "*.java"` || exit 1
    for CLASS in `find src-test -name "Test*.java" | grep -v TestData.java`; do
	CLASS=${CLASS#src-test/}
	CLASS=${CLASS%\.java}
	CLASS=`echo ${CLASS} | tr '/' '.'`
	echo $CLASS
	java -cp ${TESTLIBS} org.junit.runner.JUnitCore ${CLASS}
    done
    echo "Done testing!"
fi
