// generated by GenTs; do not edit!
import {TextSpanStyle} from "./ui/create/createTextSpanIndicator";
interface InitSettings {
  editorContents?: string;
  lightTheme?: boolean;
  captureStdio?: boolean;
  captureTraces?: boolean;
  autoflushTraces?: boolean;
  duplicateProbeOnAttrClick?: boolean;
  showAllProperties?: boolean;
  positionRecoveryStrategy?: string;
  astCacheStrategy?: string;
  syntaxHighlighting?: SyntaxHighlightingLanguageId;
  mainArgsOverride?: null | string[];
  customFileSuffix?: null | string;
  locationStyle?: null | TextSpanStyle;
  hideSettingsPanel?: boolean;
}


export {
   InitSettings
}
